version: '3'
volumes:
  venv:
    driver: local
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    environment:
      SERVER_NAME: localhost
      HOST_NAME: localhost
      DEVELOPMENT: "true"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/ssl:/etc/nginx/ssl"
    links:
      - app
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: web_app
            MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/mysql/:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    volumes:
      - venv:/data
  app:
    build: .
    hostname: app
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    links:
      - db
      - redis
    environment:
      NODE_ENV: development
    volumes:
      - .:/web_app
      - venv:/web_app/node_modules

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24
