version: '3'
volumes:
  venv:
    driver: local
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - app
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: web_app
            MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/mysql/:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis/:/data
  app:
    build: .
    ports:
      - "8080:3000"
    links:
      - db
      - redis
    environment:
      NODE_ENV: development
    volumes:
      - .:/web_app
      - venv:/web_app/node_modules
