version: 2

jobs:
  build_and_test:
    working_directory: ~/web_app
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-web_app-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-web_app-
      - run:
          name: Start
          command: 'echo start build and test'
      - run:
          name: Build
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-web_app-{{ checksum "package.json" }}
      - run:
          name: Start test
          command: npm test
  build_python:
    working_directory: ~/web_app/notebook
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache:
          key: python3-dependencies-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --deploy
      - save_cache:
          key: python3-dependencies-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
  deploy_if_on_master:
    machine: true
    working_directory: ~/web_app
    steps:
      - checkout
      - run:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                echo deploy master;
                npm install pm2 -g;
                pm2 deploy ecosystem.json production
                curl -X POST --data-urlencode "payload={\"username\": \"circleCI\",\"text\": \"deploy master branch\", \"icon_emoji\": \":ghost:\" }" "${SLACK_WEB_HOOK}"
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
      - build_python
      - deploy_if_on_master:
         requires:
            - build_and_test
         filters:
           branches:
            only: master

experimental:
  notify:
    branches:
      only:
        - master
