version: 2.1

jobs:
  build:
    working_directory: ~/web_app
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run:
          name: test
          command: 'echo empty test'
